# Generated by Django 5.0.6 on 2026-05-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_type', models.CharField(choices=[('dorm', 'Thẻ KTX'), ('parking', 'Thẻ gửi xe')], max_length=20)),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('locked', 'Đã khóa'), ('lost', 'Báo mất')], default='active', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_type', models.CharField(choices=[('dorm', 'Thẻ KTX'), ('parking', 'Thẻ gửi xe')], max_length=20)),
                ('request_type', models.CharField(choices=[('new', 'Cấp mới'), ('reissue', 'Cấp lại (mất/hỏng)'), ('extend', 'Gia hạn')], default='reissue', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('approved', 'Đã duyệt'), ('rejected', 'Đã từ chối'), ('completed', 'Đã cấp thẻ')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_requests', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
