# Generated by Django 5.0.6 on 2026-05-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('violation_date', models.DateField()),
                ('level', models.CharField(choices=[('light', 'Nhẹ'), ('medium', 'Trung bình'), ('severe', 'Nặng'), ('critical', 'Rất nặng')], default='light', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('resolved', 'Đã xử lý'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('penalty', models.CharField(blank=True, help_text='Hình thức xử phạt', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='students.student')),
            ],
            options={
                'ordering': ['-violation_date', '-created_at'],
            },
        ),
    ]
