# Generated by Django 5.0.6 on 2026-05-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_payment_and_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormitoryregistration',
            name='permanent_district',
        ),
        migrations.RemoveField(
            model_name='dormitoryregistration',
            name='permanent_province',
        ),
        migrations.RemoveField(
            model_name='dormitoryregistration',
            name='permanent_ward',
        ),
        migrations.AddField(
            model_name='dormitoryregistration',
            name='department',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='dormitoryregistration',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
