# Generated by Django 5.0.6 on 2026-05-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_room_gender'),
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electricity', 'Điện'), ('water', 'Nước'), ('furniture', 'Cơ sở vật chất'), ('internet', 'Internet'), ('other', 'Khác')], default='other', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('in_progress', 'Đang xử lý'), ('resolved', 'Đã xong'), ('closed', 'Đã đóng')], default='pending', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.URLField(blank=True, help_text='Link ảnh minh chứng sự cố', max_length=500)),
                ('admin_note', models.TextField(blank=True, help_text='Ghi chú từ admin/kỹ thuật')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='rooms.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to='students.student')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
