export const formFields = {
  buildings: [
    ["name", "Ten toa"],
    ["code", "Ma toa"],
    ["address", "Khu vuc"],
    ["manager_name", "Nguoi quan ly"],
    ["is_active", "Dang hoat dong"],
  ],
  rooms: [
    ["code", "Ma phong"],
    ["floor", "ID tang"],
    ["room_type", "Loai phong"],
    ["capacity", "Suc chua"],
    ["current_occupancy", "Dang o"],
    ["monthly_price", "Gia/thang"],
    ["gender", "Gioi tinh"],
    ["status", "Trang thai"],
  ],
  students: [
    ["student_code", "MSSV"],
    ["full_name", "Ho ten"],
    ["email", "Email"],
    ["phone", "So dien thoai"],
    ["room", "ID phong"],
    ["registered_at", "Ngay dang ky"],
    ["status", "Trang thai"],
  ],
  announcements: [
    ["title", "Tieu de"],
    ["content", "Noi dung"],
    ["target_audience", "Doi tuong"],
    ["status", "Trang thai"],
    ["is_urgent", "Khan cap"],
  ],
  violations: [
    ["student", "ID sinh vien"],
    ["title", "Ten vi pham"],
    ["description", "Mo ta"],
    ["notes", "Doi tuong vi pham"],
    ["violation_date", "Ngay vi pham"],
    ["status", "Trang thai"],
    ["penalty", "Hinh thuc xu phat"],
  ],
  incidents: [
    ["student", "ID sinh vien"],
    ["room", "ID phong"],
    ["title", "Tieu de"],
    ["description", "Khu vuc va mo ta su co"],
    ["priority", "Muc do uu tien"],
    ["status", "Trang thai"],
    ["image", "Link anh"],
    ["admin_note", "Ghi chu admin"],
  ],
  invoices: [
    ["room", "Phong"],
    ["month", "Thang"],
    ["year", "Nam"],
    ["electricity_reading", "Chi so dien moi"],
    ["water_reading", "Chi so nuoc moi"],
    ["due_date", "Han thanh toan"],
  ],
  services: [
    ["name", "Ten dich vu"],
    ["unit", "Don vi"],
    ["price", "Don gia"],
    ["is_active", "Trang thai"],
  ],
  cards: [
    ["student", "ID sinh vien"],
    ["card_type", "Loai the"],
    ["card_number", "Ma so the"],
    ["status", "Trang thai"],
    ["expiry_date", "Ngay het han"],
  ],
  card_requests: [
    ["admin_note", "Ghi chu admin"],
    ["status", "Trang thai xu ly"],
  ],
};
