export const formFields = {
  buildings: [
    ["name", "Tên tòa"],
    ["code", "Mã tòa"],
    ["address", "Khu vực"],
    ["manager", "Người quản lý"],
    ["floors", "Số tầng"],
    ["rooms", "Số phòng"],
    ["status", "Trạng thái"],
  ],
  rooms: [
    ["code", "Mã phòng"],
    ["building", "Tòa nhà"],
    ["floor", "Tầng"],
    ["type", "Loại phòng"],
    ["capacity", "Sức chứa"],
    ["occupied", "Đang ở"],
    ["price", "Giá/tháng"],
    ["status", "Trạng thái"],
  ],
  students: [
    ["code", "MSSV"],
    ["name", "Họ tên"],
    ["email", "Email"],
    ["phone", "Số điện thoại"],
    ["room", "Phòng"],
    ["building", "Tòa nhà"],
    ["registeredAt", "Ngày đăng ký"],
    ["status", "Trạng thái"],
  ],
  announcements: [
    ["title", "Tiêu đề"],
    ["audience", "Đối tượng"],
    ["createdAt", "Ngày tạo"],
    ["status", "Trạng thái"],
    ["urgent", "Khẩn cấp"],
  ],
  services: [
    ["name", "Tên dịch vụ"],
    ["code", "Mã dịch vụ"],
    ["unit", "Đơn vị"],
    ["price", "Đơn giá"],
    ["cycle", "Chu kỳ tính"],
    ["required", "Bắt buộc"],
    ["status", "Trạng thái"],
  ],
};
