# Generated by Django 5.0.6 on 2026-05-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_room_gender'),
        ('services', '0001_initial'),
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('room_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('electricity_usage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('electricity_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('water_usage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('water_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('service_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='rooms.room')),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
                'unique_together': {('room', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='services.utilityservice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_subscriptions', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UtilityUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('electricity_reading', models.DecimalField(decimal_places=2, help_text='Chỉ số điện (kWh)', max_digits=12)),
                ('water_reading', models.DecimalField(decimal_places=2, help_text='Chỉ số nước (m3)', max_digits=12)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_usages', to='rooms.room')),
            ],
            options={
                'ordering': ['-year', '-month', 'room'],
                'unique_together': {('room', 'month', 'year')},
            },
        ),
    ]
